server:
  port: 8762

spring:
  application:
    name: eureka-client

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/